<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>SIM | BlueWhale Admin</title>

<?php $this->load->view('admin/layout/header.phtml');?>
 <!--  -->	<script src="<?php echo base_url();?>skin/backend/js/jquery-ui/jquery.ui.mouse.min.js" type="text/javascript"></script>
    <script src="<?php echo base_url();?>skin/backend/js/jquery-ui/jquery.ui.sortable.min.js" type="text/javascript"></script>
    <script src="<?php echo base_url();?>skin/backend/js/table/jquery.dataTables.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            setupLeftMenu();
            $('.datatable').dataTable();
			setSidebarHeight();
        });
    </script>
</head>
<body>
  <?php $this->load->view('admin/layout/nav-main.phtml');?>
    <div class="container">

      <div align="center" class="panel panel-success">
            <div class="panel-heading"><h2 align="center" class="panel-title">Xóa trùng</h2></div>
            <div class="panel-body" align="center">
					<?php if (!isset($del)){?>
					<form action="<?php echo base_url()?>admin/sim/delduplicate" method="post">
 					<input type="radio" checked="checked" value="min" name="c">Để lại số giá bán cao nhất<br>
  					<input type="radio" value="max" name="c">Để lại số giá bán thấp nhất</div>
  					<input type="submit" class="btn btn-sm btn-danger" name="start" value="Bắt đầu"/>
  					</form>
  					<?php } else {
  						foreach ($del as $d){
  					 		echo 'Đã xóa số'.$d->sim_split;
  						}
  						}?>
  					 
      		</div>
      </div>
  </div>
  
  </body>
  </html>