<form method="Get" action="index.php" class="form-inline">
<input type="hidden" name="act" value="baogia">
<div class="panel panel-success">
  <div class="panel-heading">
    <h2 class="panel-title">Tìm kiếm</h2>
  </div>
  <div class="panel-body">
<table class="table table-bordered" style="width: 100%">
		<tr>
			<td><select name="post[dauso]" class="form-control input-sm">
			<option value="0" selected="selected">Đầu số</option>
			<option value="0997">0997</option>
<option value="0996">0996</option>
<option value="0995">0995</option>
<option value="0994">0994</option>
<option value="0993">0993</option>
<option value="0990">0990</option>
<option value="0989">0989</option>
<option value="0988">0988</option>
<option value="0987">0987</option>
<option value="0986">0986</option>
<option value="0985">0985</option>
<option value="0984">0984</option>
<option value="0983">0983</option>
<option value="0982">0982</option>
<option value="0981">0981</option>
<option value="0980">0980</option>
<option value="0979">0979</option>
<option value="0978">0978</option>
<option value="0977">0977</option>
<option value="0976">0976</option>
<option value="0975">0975</option>
<option value="0974">0974</option>
<option value="0973">0973</option>
<option value="0972">0972</option>
<option value="0971">0971</option>
<option value="0970">0970</option>
<option value="0969">0969</option>
<option value="0968">0968</option>
<option value="0967">0967</option>
<option value="0966">0966</option>
<option value="0965">0965</option>
<option value="0964">0964</option>
<option value="0963">0963</option>
<option value="0962">0962</option>
<option value="0961">0961</option>
<option value="0960">0960</option>
<option value="0959">0959</option>
<option value="0958">0958</option>
<option value="0957">0957</option>
<option value="0956">0956</option>
<option value="0955">0955</option>
<option value="0954">0954</option>
<option value="0953">0953</option>
<option value="0952">0952</option>
<option value="0949">0949</option>
<option value="0948">0948</option>
<option value="0947">0947</option>
<option value="0946">0946</option>
<option value="0945">0945</option>
<option value="0944">0944</option>
<option value="0943">0943</option>
<option value="0942">0942</option>
<option value="0939">0939</option>
<option value="0938">0938</option>
<option value="0937">0937</option>
<option value="0936">0936</option>
<option value="0935">0935</option>
<option value="0934">0934</option>
<option value="0933">0933</option>
<option value="0932">0932</option>
<option value="0931">0931</option>
<option value="0930">0930</option>
<option value="0929">0929</option>
<option value="0928">0928</option>
<option value="0927">0927</option>
<option value="0926">0926</option>
<option value="0925">0925</option>
<option value="0924">0924</option>
<option value="0923">0923</option>
<option value="0922">0922</option>
<option value="0919">0919</option>
<option value="0918">0918</option>
<option value="0917">0917</option>
<option value="0916">0916</option>
<option value="0915">0915</option>
<option value="0914">0914</option>
<option value="0913">0913</option>
<option value="0912">0912</option>
<option value="0909">0909</option>
<option value="0908">0908</option>
<option value="0907">0907</option>
<option value="0906">0906</option>
<option value="0905">0905</option>
<option value="0904">0904</option>
<option value="0903">0903</option>
<option value="0902">0902</option>
<option value="0901">0901</option>
<option value="0897">0897</option>
<option value="0896">0896</option>
<option value="0884">0884</option>
<option value="0872">0872</option>
<option value="0866">0866</option>
<option value="0862">0862</option>
<option value="0858">0858</option>
<option value="0838">0838</option>
<option value="0836">0836</option>
<option value="0835">0835</option>
<option value="0822">0822</option>
<option value="0812">0812</option>
<option value="0488">0488</option>
<option value="0485">0485</option>
<option value="0466">0466</option>
<option value="0463">0463</option>
<option value="0462">0462</option>
<option value="0461">0461</option>
<option value="0445">0445</option>
<option value="0444">0444</option>
<option value="0439">0439</option>
<option value="0438">0438</option>
<option value="0437">0437</option>
<option value="0436">0436</option>
<option value="0435">0435</option>
<option value="0433">0433</option>
<option value="0432">0432</option>
<option value="0423">0423</option>
<option value="0422">0422</option>
<option value="0420">0420</option>
<option value="0199">0199</option>
<option value="0198">0198</option>
<option value="0197">0197</option>
<option value="0196">0196</option>
<option value="0195">0195</option>
<option value="0193">0193</option>
<option value="0192">0192</option>
<option value="0191">0191</option>
<option value="0188">0188</option>
<option value="0186">0186</option>
<option value="0169">0169</option>
<option value="0168">0168</option>
<option value="0167">0167</option>
<option value="0166">0166</option>
<option value="0165">0165</option>
<option value="0164">0164</option>
<option value="0163">0163</option>
<option value="0162">0162</option>
<option value="0129">0129</option>
<option value="0128">0128</option>
<option value="0127">0127</option>
<option value="0126">0126</option>
<option value="0125">0125</option>
<option value="0124">0124</option>
<option value="0123">0123</option>
<option value="0122">0122</option>
<option value="0121">0121</option>
<option value="0120">0120</option>
<option value=""></option>
</select>
<select class="form-control input-sm" name="post[loaisim]">
			<option value="0" selected="selected" class="form-control input-sm">Loại sim</option>
			<option value="Sim Lục Quý">Sim Lục Quý</option>
<option value="Sim Ngũ Quý">Sim Ngũ Quý</option>
<option value="Sim Tứ Quý">Sim Tứ Quý</option>
<option value="Sim Tam Hoa">Sim Tam Hoa</option>
<option value="Tam Hoa Kép">Tam Hoa Kép</option>
<option value="Số Taxi 2">Số Taxi 2</option>
<option value="Số Taxi 3">Số Taxi 3</option>
<option value="Số Taxi 4">Số Taxi 4</option>
<option value="Sim Năm Sinh 19xx">Sim Năm Sinh 19xx</option>
<option value="Sim Ngày/Tháng/Năm Sinh">Sim Ngày/Tháng/Năm Sinh</option>
<option value="Số tiến đơn">Số tiến đơn</option>
<option value="Số Tiến đôi">Số Tiến đôi</option>
<option value="Số Lộc Phát">Số Lộc Phát</option>
<option value="Số Thần Tài">Số Thần Tài</option>
<option value="Số ông địa">Số ông địa</option>
<option value="Số kép">Số kép</option>
<option value="Số Lặp">Số Lặp</option>
<option value="Số Đảo">Số Đảo</option>
<option value="Số gánh">Số gánh</option>
<option value="Số đối">Số đối</option>
<option value="Sim Đặc Biệt">Sim Đặc Biệt</option>
<option value="Đầu số cổ">Đầu số cổ</option>
<option value="Tam Hoa Đơn">Tam Hoa Đơn</option>
</select>
			<select class="form-control input-sm" name="post[daily]">
			<option value="0" selected="selected" class="form-control input-sm">Đại lý</option>
			<option value="274"> Thiên hà (01246.456.789 01698.39.39.39 - 0962.168.186) -simsodepthienha.com</option>

</select>
			<select class="form-control input-sm" name="post[oder]" style="width: 122px">
			<option value="order by giaban desc">Giảm</option>
			<option value="order by giaban asc">Tăng</option>
			</select>
			<input name="post[search]" type="text" class="form-control input-sm" style="width: 64px;">
			<input name="submit" type="submit" value="Tìm kiếm" class="btn btn-success"> 0</td>
		</tr>
	</table>
  </div>
</div>
	</form>