<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?php echo base_url()?></title>

<?php $this->load->view('admin/layout/header.phtml');?>
 <!--  -->	<script src="<?php echo base_url();?>skin/backend/js/jquery-ui/jquery.ui.mouse.min.js" type="text/javascript"></script>
    <script src="<?php echo base_url();?>skin/backend/js/jquery-ui/jquery.ui.sortable.min.js" type="text/javascript"></script>
    <script src="<?php echo base_url();?>skin/backend/js/table/jquery.dataTables.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            setupLeftMenu();
            $('.datatable').dataTable();
			setSidebarHeight();
        });
    </script>
</head>
<body>
  <?php $this->load->view('admin/layout/nav-main.phtml');?>
    <div class="container">

      <div class="panel panel-success">
            <div class="panel-heading"><h2 align="center" class="panel-title">Nhập SIM</h2></div>
            <div class="panel-body" align="center">
                <div class="block ">
                    <form action="<?php echo base_url()?>admin/sim/import" method="post" >
	                    <table class="form">
	                        <tr>
	                            <td class="col1">
	                                <label>Nhập SIM và giá</label><br/>
	                                 <p>Chú ý: giá phân cách nhau bằng dấu phẩy</p>
	                            </td>
	                            <td class="col2">
	                                <textarea style="width: 250px;height: 245px"  name="datasim"></textarea>
	                            </td>
	                        </tr>
	                         <tr>
	                         <tr>
                            <td>
                                <p>Phần trăm(%) giá bán</p>
                            </td>
                            <td>
                                <?php if(isset($sellpercent)){
                            	 	foreach ($sellpercent as $sp){
                            	
	                            		$lower = $sp->lower;
                            	 	if(strlen($lower)>9){
	                            			$lower = substr($lower, 0,strlen($lower)-9).','.substr($lower,-9,3).','.substr($lower,-6,3).','.substr($lower,-3,3);
	                            		}else if (strlen($lower)>6 ){
	                            			$lower = substr($lower, 0,strlen($lower)-6).','.substr($lower,-6,3).','.substr($lower,-3,3);
	                            		} else if (strlen($lower)>3){
											$lower = substr($lower, 0,strlen($lower)-3).','.substr($lower,-3,3);
										}
										
										$upper = $sp->upper;
                            	 	if(strlen($upper)>9){
	                            			$upper = substr($upper, 0,strlen($upper)-9).','.substr($upper,-9,3).','.substr($upper,-6,3).','.substr($upper,-3,3);
	                            		}else if (strlen($lower)>6 ){
	                            			$upper = substr($upper, 0,strlen($upper)-6).','.substr($upper,-6,3).','.substr($upper,-3,3);
	                            		} else if (strlen($lower)>3){
											$upper = substr($upper, 0,strlen($upper)-3).','.substr($upper,-3,3);
										}
                            	?>
                          		<p><?php echo $lower.'-'.$upper.': '.$sp->percent.'%'?></p>
                                <?php }//End of foreach ($sellpercent as $sp)?>
                                <?php }//end of if(isset($sellpercent)?>
                            </td>
                        	</tr>
                        	<tr>
                            <td>
                                <label>Đại lý</label>
                            </td>
                            <td>
                            	<select id="agency" name="agency" onchange="this.form.submit()">
                            	<?php if (isset($agency)){?>
	                            	<?php foreach ($agency as $a){?>                            	                                                                                                  
	                                    <option value="<?php echo $a->profileid?>" <?php if (isset($agencypercent) && ($agencypercent[0]->profileid == $a->profileid)) echo "selected=\"selected\";"?>><?php echo $a->agencyname?></option>                                                                    
	                                <?php }//End of foreach ($agency as $a)?>
                                <?php } ?>
                                	
                                </select>
                            </td>
                        </tr>
                        <tr>
	                        <td><p>Phần trăm(%) đại lý</labe></p></td>
	                            <?php if (isset($agencypercent)){?>
	                        
	                        		<td><?php foreach ($agencypercent as $arr){?>
	                        		<?php  		$lower = $arr->lower;
	                            		if(strlen($lower)>9){
		                            			$lower = substr($lower, 0,strlen($lower)-9).','.substr($lower,-9,3).','.substr($lower,-6,3).','.substr($lower,-3,3);
		                            		}else if (strlen($lower)>6 ){
		                            			$lower = substr($lower, 0,strlen($lower)-6).','.substr($lower,-6,3).','.substr($lower,-3,3);
		                            		} else if (strlen($lower)>3){
												$lower = substr($lower, 0,strlen($lower)-3).','.substr($lower,-3,3);
											}
											
											$upper = $arr->upper;
												if(strlen($upper)>9){
		                            			$upper = substr($upper, 0,strlen($upper)-9).','.substr($upper,-9,3).','.substr($upper,-6,3).','.substr($upper,-3,3);
		                            		}else if (strlen($lower)>6 ){
		                            			$upper = substr($upper, 0,strlen($upper)-6).','.substr($upper,-6,3).','.substr($upper,-3,3);
		                            		} else if (strlen($lower)>3){
												$upper = substr($upper, 0,strlen($upper)-3).','.substr($upper,-3,3);
											}
                            		?>
									<p style="margin-bottom: 0px">
										<?php echo $lower.' - '.$upper.": ".$arr->percent."%";?>
									</p>
									<?php }?>
								<?php }//End of if (isset($agencypercent))?>
							</td>
                        </tr>
	                       </table>
                         <input class="btn btn-success" type="submit" value="Nhập"/>
                       </form>
                </div>
      		</div>
      </div>
  </div>
  
  </body>
  </html>