<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0" charset="utf8">

</head>
<body style="background-image: url('<?php echo base_url()?>skin/backend/img/15-outer-space-wallpaper.jpg')">
	<div align="center" style="margin-top: 20%">
		<form  action="<?php echo base_url()?>admin" method="post">
		<p><strong style="color: white">Tên truy nhập: </strong><input type="text" name="username" value=""></p>
		<p><strong style="color: white">Mật khẩu: </strong><input type="password" name="password" value=""></p>
		<div class="clearfix"></div>
		<input type="submit" name="submit" value="Đăng nhập">
		</form>
	</div>
</body>