<script>winndow.location='index.php';</script><!DOCTYPE html>
<html lang="vi, en">
<?php $this->load->view('admin/layout/header.phtml')?>

<body>
<?php $this->load->view('admin/layout/modal.phtml')?>

<!-- Modal -->
<div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
 <a  data-dismiss="modal"><span aria-hidden="true">&times;</span></a>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body">
       <iframe id="iframe" src="" frameborder="0" height="400" width="100%"></iframe>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
    
      </div>
    </div>
  </div>
</div>


<?php $this->load->view('admin/layout/nav-main.phtml');?>

<div class="container-fluid">
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Đơn đặt hàng</h3>
  </div>
  <div class="panel-body">
<?php $this->load->view('admin/order/search.phtml')?>
  </div>
</div>
 
<form method="post" class="table-responsive">
<table class="table table-bordered table-hover table-condensed">

<thead>
	<tr>
	<th class="active"></th>
		<th class="active">Họ tên</th>
        <th class="active">Điện thoại</th>
        <th class="active">Địa chỉ</th>
        <th class="active">Email</th>
        <th class="active">Sim đặt hàng</th>
        <th class="active">Tổng tiền</th>
        <th class="active hidden-xs">Ngaỳ đặt hàng</th>
	</tr>
    <?php foreach ($order as $o){?>
    
    
            <tr>
   			<td class="center"><?php echo $o->orderid?></td>
     		<td><?php echo $o->fullname?></td>
     		<td><?php echo $o->phone?></td>
     		<td><?php echo $o->address?></td>
     		<td><?php echo $o->email?></td>
      	 	<td>
      	 	<?php $total_price = 0;?>
      	 		<?php foreach ($order_detail as $od){?>
      	 		<?php if ($od->order_id == $o->orderid){?>
      	 		<strong><span  
      	 		style="<?php 
      	 			if ($od->od_status == 'deliver') echo 'color: #0066FF';
      	 			if ($od->od_status == 'pending') echo 'color: red';
      	 			if ($od->od_status == 'failure') echo 'color: yellow';
      	 		?>"><?php echo $od->sim_split?></span></strong><br/>
      	 		<?php $total_price += $od->price_sell?>
      	 		<?php }?>
				<?php }?>
			</td>
													<?php 
										//caculator total price and split by ','
										if(strlen($total_price)>9){
	                            			$total_price = substr($total_price, 0,strlen($total_price)-9).','.substr($total_price,-9,3).','.substr($total_price,-6,3).','.substr($total_price,-3,3);
	                            		}else if (strlen($total_price)>6 ){
	                            			$total_price = substr($total_price, 0,strlen($total_price)-6).','.substr($total_price,-6,3).','.substr($total_price,-3,3);
	                            		} else if (strlen($total_price)>3){
											$total_price = substr($total_price, 0,strlen($total_price)-3).','.substr($total_price,-3,3);
										}
										?>
                <td><?php echo $total_price;?></td>
                <td><?php echo $o->datetime;?></td>

                
                     
                
    </tr>
           <?php }?>
    </thead>

</table>


</form>

<div id='paging'><?php  echo $pagination; ?></div>
</div>
</body>






</html>
