<meta name="viewport" content="width=device-width, initial-scale=1.0" charset="utf8">
<title>Administrator</title>
<link rel="stylesheet" type="text/css" href="<?php echo base_url()?>skin/backend/css/default.css" />
<link rel="stylesheet" type="text/css" href="<?php echo base_url()?>skin/backend/css/style.css" />
<link rel="stylesheet" type="text/css" href="<?php echo base_url()?>skin/backend/css/cssmenu.css" />
<link rel="stylesheet" type="text/css" href="<?php echo base_url()?>skin/backend/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo base_url()?>skin/backend/css/bootstrap-theme.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo base_url()?>skin/backend/css/admin_table.css" />

<script type="text/javascript" src="<?php echo base_url()?>skin/backend/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo base_url()?>skin/backend/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo base_url()?>skin/backend/js/bootstrap-hover-dropdown.js"></script>
<script type="text/javascript" src="<?php echo base_url()?>skin/backend/js/admin.js"></script>
<script type="text/javascript" src="<?php echo base_url()?>skin/backend/js/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>

