<div class="modal fade" id="minimodal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
  <a class="glyphicon glyphicon-remove pull-right" data-dismiss="modal"></a>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
    
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
 
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->