<head>
	<meta content="P6QisiCUEk98FMNpeHAqKSHkezf_xfPC_M_PD2pEnJ8" name="google-site-verification">
	<title>SIM SỐ ĐẸP, đại lý sim số đẹp giá rẻ nhất - Sovip.com.vn</title>
	<meta content="width=device-width, initial-scale=1" name="viewport" charset="utf-8">
	<meta content="public, max-age=86400" http-equiv="Cache-control">
	<meta content="SIM SỐ ĐẸP mạng ✔Viettel ✔Vinaphone ✔Mobiphone... giá rẻ tại Hà Nội. Đại lý phân phối sim số đẹp, hỗ trợ đăng ký chính chủ - L/H: 0944.66.8888" name="description">
	<meta content=" sim so dep, simsovip.com, sim số đẹp, sim số, sim số đẹp viettel, sim số đẹp vinaphone, sim số đẹp Mobiphone " name="keywords">
	<meta content="tongstv" name="author">
	<base href="<?php echo base_url()?>">
	<script async="async" src="<?php echo base_url()?>skin/frontend/js/analytics.js"></script>
	<script async="async" src="<?php echo base_url()?>skin/frontend/js/jquery.min.js"></script>
	<script async="async" src="<?php echo base_url()?>skin/frontend/js/bootstrap.min.js">
	<script async="async" src="<?php echo base_url()?>skin/frontend/js/bootstrap-datepicker.js"></script>
	<script async="async" src="<?php echo base_url()?>skin/frontend//js/scriptlibs.js"></script>
	<script async="async" src="<?php echo base_url()?>skin/frontend//js/script.min.js"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo base_url();?>skin/frontend/css/global.css" media="screen" />
</head>
<body>
<?php $this->load->view('frontend/layout/fixed_navbar.phtml')?>
	<div class="clearfix"></div>
<div class="container container-fix">
		<div class="row">
			<div class="col-md-9" style="max-width: 694px">
				<div class="panel-fix">
					<div class="panel-heading">
						<h1 class="panel-title">Hỗ Trợ Mua Sim</h1>
					</div>
					<div class="panel-body">
					
					
						<div class="table-condensed"><p>Qúy khách cần thêm thông tin, cần được biết về cách thức mua <a href="http://sodep.vn">sim số đẹp</a>....</p><p>Đừng ngần ngại hãy nhấc máy gọi ngay cho chúng tôi để được hỗ trợ tốt nhất (24/24).</p><p><strong>SỐ MÁY HỖ TRỢ</strong></p><p><strong>Quản lý : 0933.999999 - 0944.888888 ( Mr Hiếu )</strong></p><p><strong>Bán hàng : 0944.66.8888 - 0944.66.9999 ( Mr Nam )</strong></p><p><strong>Kinh doanh : 093.444.8888 - 094.555.9999 - 0944.68.68.68 ( Mr Trung )</strong></p><p><strong>Công nợ : 094.66.99999 ( Ms Nga )</strong></p><p><strong>Chuyển phát : 09.46.46.46.46 ( Mr Tùng )</strong></p></div>
					</div>

				</div>
			</div>
			<?php //$this->load->view('frontend/layout/right.phtml')?>
			<div class="clearfix"></div>
			<!-- Tạm thời cho trỏ về sovip.com.vn -->
			<?php $this->load->view('frontend/layout/content-bottom.phtml')?>
			<div class="clearfix"></div>
		
			<?php $this->load->view('frontend/layout/footer.phtml')?>
			<div class="clearfix"></div>
		</div>
	</div>
	</body>