	<meta content="P6QisiCUEk98FMNpeHAqKSHkezf_xfPC_M_PD2pEnJ8" name="google-site-verification">

	<meta content="width=device-width, initial-scale=1" name="viewport" charset="utf-8">
	<meta content="public, max-age=86400" http-equiv="Cache-control">
	<meta content="SIM SỐ ĐẸP mạng ✔Viettel ✔Vinaphone ✔Mobiphone... giá rẻ tại Hà Nội. Đại lý phân phối sim số đẹp, hỗ trợ đăng ký chính chủ - L/H: 0944.66.8888" name="description">
	<meta content=" sim so dep, simsovip.com, sim số đẹp, sim số, sim số đẹp viettel, sim số đẹp vinaphone, sim số đẹp Mobiphone " name="keywords">
	<meta content="tongstv" name="author">
		<script  src="<?php echo base_url()?>skin/frontend/js/jquery.min.js"></script>
	
	<script async="async" src="<?php echo base_url()?>skin/frontend/js/analytics.js"></script>
	
	<script  src="<?php echo base_url()?>skin/frontend/js/bootstrap.min.js"></script>
	<script  src="<?php echo base_url()?>skin/frontend/js/bootstrap-datepicker.js"></script>
	<script  src="<?php echo base_url()?>skin/frontend//js/scriptlibs.js"></script>
	<script  src="<?php echo base_url()?>skin/frontend//js/script.min.js"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo base_url();?>skin/frontend/css/global.css" media="screen" />