<form action="<?php echo base_url()?>order/mua-sim-trong-gio-hang.html" method='post'>
<div class="container-fluid">
	<div aria-hidden="false" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade in" >
		<div class="modal-backdrop fade in"></div>
			<div class="modal-dialog">
				<div class="modal-content">   
		    		<div class="modal-content">
				      	<div class="modal-header">
					        <button data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
					        <h4 id="myModalLabel" class="modal-title">Giỏ hàng của bạn</h4>
				      	</div>
				      	<div class="modal-body">
				      	
						    <table id="tableorder"class="table table-condensed table-bordered table-striped">
								<thead>
							        <tr>
								        <th class="active text-center"></th>
								        <th class="active">Số sim</th>
								        <th class="active">Giá tiền (VNĐ)</th>
								        <th class="active"></th>
							    	</tr>
						    	</thead>
						    
						            
						    <tbody>
						     <!--        
						    <tr>
						        <td class="text-center">2</td>
						        <td><label id="order_sim"></label></td>
						        <td><label id="order_price" > VNĐ</label></td>
						        <td class="text-center"><a data-sim="01299998888" class="delcart" href="javascript://"> <i class="glyphicon glyphicon-trash text-danger"></i></a></td>
						    </tr>
						           -->  
						   

						    </tbody>
						    </table>  
						    						      <!--       <tr>
						    <td colspan="4" class="active">
						    <h5 class="pull-right">
						    Tổng tiền: <span id="total_price">980,000,000</span> VNĐ
						    </h5>
						    </td>
						    </tr>   -->
				      	</div>
			      		<div class="modal-footer">
				        	<button data-dismiss="modal" class="btn btn-info" type="button">Chọn tiếp</button>
			                <button type="submit"><a class="btn btn-success" >Mua sim trong giỏ</a></button>
		              	</div>
		    		</div>      
		    	</div>
		    </div>
	</div>
</div>
</form>