	<nav class="navbar navbar-default" role="navigation">
		<div class="navbar-header">
		<a class="narbar-brand" href="<?php echo base_url()?>">
				<?php if (isset($pagecontent)){?>
			<?php foreach ($pagecontent as $pc){?>
				<?php if ($pc->location=='nav'){?>
				<?php echo $pc->content?>
		
				<?php }?>
			<?php }?>
		<?php }?>
		</a>
		</div>
		<div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<?php foreach ($providers as $prv){?>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown">
						<span class=""></span><?php echo $prv->name;?><span class="caret"></span>
					</a>
					<ul class="dropdown-menu mega-menu" role="menu" style="opacity: 1">
						<li class="mega-menu-column">
							<ul>
								<?php foreach($kinds as $k){?>
								<li> 
									<a href="<?php echo base_url().$prv->name.'/'.$k->name.'.html'?>">
									<span class="glyphicon glyphicon-arrow-right"></span><?php echo $k->fullname?>
									</a>
								</li>
								<?php }?>
							</ul>
						</li>
					
					</ul>
				</li>
				<?php }//End of foreach ($providers as $prv)?>
			</ul>
		</div>
	</nav>