<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
 <meta http-equiv="Content-Type" content="text/html; charset="UTF-8">
 <?php $this->load->view('admin/layout/header.phtml');?>

    <script type="text/javascript">
        function validateForm() {
            var x = document.forms["myForm"]["title"].value;
            if (x == null || x == "") {
                alert("Chưa nhập tiêu đề!");
                return false;
            }
        }
    </script>
    <!-- WYSIWYG Editor -->
   <!-- Load TinyMCE -->
    <script src="<?php echo base_url()?>skin/backend/js/tiny-mce/jquery.tinymce.js" type="text/javascript"></script>
    <script type="text/javascript">
    function setupTinyMCE() {
        $('textarea.tinymce').tinymce({
            // Location of TinyMCE script
            script_url: '<?php echo base_url()?>skin/backend/js/tiny-mce/tiny_mce.js',

            // General options
            theme: "advanced",
            plugins: "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

            // Theme options
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: true,

            // Example content CSS (should be your site CSS)
           // content_css: "css/content.css",

            // Drop lists for link/image/media/template dialogs
            template_external_list_url: "lists/template_list.js",
            external_link_list_url: "lists/link_list.js",
            external_image_list_url: "lists/image_list.js",
            media_external_list_url: "lists/media_list.js",

            // Replace values for the template plugin
            template_replace_values: {
                username: "Some User",
                staffid: "991234"
            }
        });
    }
        
        $(document).ready(function () {
            setupTinyMCE();

        });
    </script>
    <!-- /TinyMCE -->
</head>
<body>
<?php 
$locationArr = array('title',
		'nav',
		'fixed_navbar',
		'content-bottom_chinh-sach-ban-sim',
		'content-bottom_ho-tro-mua-sim',
		'content-bottom_thong-tin-sim-so-dep',
		'footer',		
		'right');
$contentbottomArr = array('Chính sách bán sim','Hỗ trợ mua sim','Thông tin về sim số đẹp');
$rightArr = array('Sim khuyến mại','Tin tức')
?>
      <div class="panel panel-success">
           
                	<?php if (isset($pagecontent)){?>
                	 <div class="panel-heading">
                <h3>Sửa liên kết</h3>
                </div>
                <div class="panel-body ">
                		
                	<?php foreach ($pagecontent as $pc){?>
                    <form name="myForm" onsubmit="return validateForm()"  action="<?php echo base_url()?>admin/pagecontent/edit/<?php echo $pc->pagecontentid?>" method="post">                                       	
	                    <table class="form">

	               			<tr>
	                            <td style="width: 92px;">
	                                <label>Tiêu đề :</label><p style="color: red; float: right">*&nbsp;</p>
	                            </td>
	                            <td>
	                                <input id="title" name="title" type="text" class="mini" value="<?php if (isset($pc->title)) echo $pc->title?>"/>
	                            </td>
                        	</tr>
                        	<tr>
                        		<td style="width: 92px;">
	                                <label>Vị trí :</label><p style="color: red; float: right">*&nbsp;</p>
	                            </td>
	                            <td>
	                                <select name="location">
	                                	<?php foreach ($locationArr as $la){?>
	                                	<option value="<?php echo $la?>"><?php echo $la?></option>
	                                	<?php }?>
	                                </select>
	                            </td>
                        	</tr>
	                         <tr>
	                          <td style="vertical-align: top; padding-top: 9px;">
                                <label>
                                    WYSIWYG Editor</label>
                            </td>
                            <td>
                                <textarea class="tinymce" name="content"><?php echo $pc->content?></textarea>
                            </td>
                        	</tr>

                        	 </table>
                         <input type="submit" value="Lưu"/>
                        </form>
                        	<?php }//End of foreach?>
                 <?php }else{?>
                 <div class="panel-heading">
                <h3>Thêm liên kết</h3>
                </div>
                <div class="panel-body ">
                    <form name="myForm" onsubmit="return validateForm()"  action="<?php echo base_url()?>admin/pagecontent/add" method="post" >
                    	       <table class="form">
                    	     

	               			<tr>
	                            <td style="width: 92px;">
	                                <label>Tiêu đề :</label><p style="color: red; float: right">*&nbsp;</p>
	                            </td>
	                            <td>
	                                <input id="title" name="title" type="text" class="mini" />
	                            </td>
                        	</tr>
                        	<tr>
                        		<td style="width: 92px;">
	                                <label>Vị trí :</label><p style="color: red; float: right">*&nbsp;</p>
	                            </td>
	                            <td>
	                                <select name="location">
	                                	<?php foreach ($locationArr as $la){?>
	                                	<option value="<?php echo $la?>"><?php echo $la?></option>
	                                	<?php }?>
	                                </select>
	                            </td>
                        	</tr>

	                         <tr>
	                      <td style="vertical-align: top; padding-top: 9px;">
                                <label>
                                    WYSIWYG Editor</label>
                            </td>
                            <td>
                                <textarea class="tinymce" name="content"></textarea>
                            </td>
                        	</tr>
                  
                        	 </table>
                         <input type="submit" value="Lưu"/>
                        </form>
                    	<?php }?>
                   
	                
                </div>
      		</div>
      </div>
  
  </body>
  </html>